apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm
  labels:
    app: backend-scm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
      - name: backend-scm
        image: theusbrz/backend-scm:alpha
        ports:
        - containerPort: 3030
        env:
        - name: NODE_ENV
          value: "staging"
        - name: SECRET_OR_KEY
          value: "b00tc@mp18"
        - name: GITHUB_CLIENT_ID
          value: "1a0e0d62fd2dd44a68e4"
        - name: GITHUB_CLIENT_SECRET
          value: "9223252d0131a42073ddc46051707be5efce3e95"